### ISSUE TITLE
Umbrella for v0.4.0

### ISSUE THREAD

**Issue by markusjwetzel** [ProAI/react-kickstarter#8]
- [x] **Babel 7 Upgrade**
This might be easy, because there are not much breaking changes between the configs of v6 and v7.

- [x] **Webpack 4 Upgrade**
There might be two replacements that we need to do:
  - Replace `extract-text-webpack-plugin` with [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) (see [this issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701))
  - Replace `webpack-isomorphic-tools` with [`isomorphic-loader`](https://github.com/electrode-io/isomorphic-loader), because `webpack-isomorphic-tools` is deprecated and not Webpack 4 compatible. Another option is to remove `webpack-isomorphic-tools` and compile server side code also with webpack. See https://github.com/DominicTobias/universal-react/blob/master/server.js.
&nbsp;

- [x] **Remove error overlay**
Error overlay for eslint errors and eslint in general is no longer needed in webpack, because nowadays eslint errors are shown in the editor and an error overlay in the browser just feels annoying sometimes.

- [x] **Add project eslint and prettier config files**
Each `react-kickstarter` project should have an `eslintrc.js` and a `prettierrc.js` file that imports the default eslint/prettier config. This way an editor can grab the configs.

- [x] **Provide `eslint` and `prettier` command**
The `eslint` and `prettier` commands should be passed through, so no installation of `eslint` or `prettier` within the project is needed.
-> *see comment below*

- [x] **Add `eslint-config-prettier`**
Use `eslint-config-prettier`(https://github.com/prettier/eslint-config-prettier) instead of `eslint --fix` after `prettier`, i.e. instead of using `prettier-eslint` (see https://twitter.com/kentcdodds/status/913760103118991361)

**Comment by markusjwetzel** [comment]
> Provide eslint and prettier command

We decided to "fake" the eslint command, but not copy over the prettier command. This is due to implementation details of the referring VSCode plugins:

`vscode-eslint`: This package looks in `node_modules/.bin` for an executable named `eslint`. `react-kickstarter` now provides such an executable that points to the `eslint` installation of `react-kickstarter`. This way we don't need to add all the `eslint` plugin and config dependencies to the project `package.json`.

`prettier-vscode`: This package searches `package.json` for a `prettier` installation. If none was found, the package will fallback to a built-in version of prettier. We want to use the same prettier version in the VSCode plugin and on precommit, so we need a prettier installation inside the project, not a built-in version in `prettier-vscode`. Since `prettier-vscode` cannot detect a prettier version installed by `react-kickstarter` we need to add prettier to the project itself for now.
